apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 9.0.17
    chart: apache
    directory:
      jsonnet:
        tlas:
          - {}
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false