apiVersion: v2
name: argo-cd
# my chart version
version: 1.0.0
dependencies:
  - name: argo-cd
    # repo chart version
    version: 4.6.1
    repository: https://argoproj.github.io/argo-helm



# kubectl get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" -n argo-cd | base64 -d